export const xml = `<?xml version="1.0" encoding="UTF-8"?>
<Package xmlns="http://soap.sforce.com/2006/04/metadata">
	<types>
		<members>*</members>
		<name>CustomMetadata</name>
	</types>
	<types>
		<members>*</members>
		<name>RecordType</name>
	</types>
	<types>
		<members>*</members>
		<name>GlobalValueSet</name>
	</types>
	<types>
		<members>*</members>
		<name>CustomField</name>
	</types>
	<types>
		<members>*</members>
		<members>Account</members>
		<members>AccountContactRelation</members>
		<members>AccountContactRole</members>
		<members>Activity</members>
		<members>Asset</members>
		<members>AssistantProgress</members>
		<members>Campaign</members>
		<members>CampaignMember</members>
		<members>Case</members>
		<members>CaseContactRole</members>
		<members>Contact</members>
		<members>ContentVersion</members>
		<members>Contract</members>
		<members>ContractContactRole</members>
		<members>DuplicateRecordItem</members>
		<members>DuplicateRecordSet</members>
		<members>EmailMessage</members>
		<members>Event</members>
		<members>ExchangeUserMapping</members>
		<members>FeedItem</members>
		<members>Idea</members>
		<members>Lead</members>
		<members>LinkedArticle</members>
		<members>Macro</members>
		<members>MacroAction</members>
		<members>MacroInstruction</members>
		<members>Opportunity</members>
		<members>OpportunityCompetitor</members>
		<members>OpportunityContactRole</members>
		<members>OpportunityLineItem</members>
		<members>Order</members>
		<members>OrderItem</members>
		<members>PartnerRole</members>
		<members>Pricebook2</members>
		<members>PricebookEntry</members>
		<members>Product2</members>
		<members>ProfileSkill</members>
		<members>ProfileSkillEndorsement</members>
		<members>ProfileSkillUser</members>
		<members>Quote</members>
		<members>QuoteLineItem</members>
		<members>Site</members>
		<members>SocialPersona</members>
		<members>Solution</members>
		<members>StreamingChannel</members>
		<members>Task</members>
		<members>Territory</members>
		<members>User</members>
		<members>WorkBadge</members>
		<members>WorkBadgeDefinition</members>
		<members>WorkThanks</members>
		<name>CustomObject</name>
	</types>
	<version>41.0</version>
</Package>`