name: "DOC - Build and deploy with sfdx-hardis"
on:
  push:
    branches:
      - main
      - master

jobs:
  # Build & deploy docs
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      # Build doc with sfdx-hardis
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: yarn
      - run: yarn prepack
      - run: npm i sfdx-cli -g
      - run: echo y|sfdx plugins:install sfdx-hardis
      - run: sfdx hardis:doc:plugin:generate
      # Deploy docs with mkdocs-material
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mdx_truly_sane_lists json-schema-for-humans
      - run: mkdocs gh-deploy --force
